#!/usr/bin/env python3
"""
Gate 3 - verifier-side defect: an internal crash, a contract-alignment defect,
or a parser hazard causally bound to the failure (`failure_binding == "direct"`).
Hard Rule 5: a hazard with no direct binding must NOT reach this gate.

Generated by extracting the corresponding region of the former
`analyze_case._build_raw_causal_attribution` verbatim; the gate bodies below are
byte-identical to the original logic.
"""
from __future__ import annotations

from confidence import attach_confidence_metadata
from runtime_state import SCHEMA_VERSION

from typing import Any, Dict, Optional

from ..context import AttributionContext



def gate3_verifier_defect(ctx: AttributionContext) -> Optional[Dict[str, Any]]:
    case_id = ctx.case_id
    runtime = ctx.runtime
    trial_name = ctx.trial_name
    verifier_defect_contracts = ctx.verifier_defect_contracts
    verifier_obs = ctx.verifier_obs

    verifier_crashes = [v for v in verifier_obs if v.get('type') == 'verifier_internal_crash']
    verifier_defects = verifier_defect_contracts
    triggered_hazards = [
        v for v in verifier_obs
        if v.get('triggered') and v.get('failure_binding') == 'direct' and v.get('type') != 'verifier_internal_crash'
    ]

    if not (verifier_crashes or verifier_defects or triggered_hazards):
        return None

    vc = verifier_crashes[0] if verifier_crashes else None
    vd = verifier_defects[0] if verifier_defects else None
    th = triggered_hazards[0] if triggered_hazards else None

    if vc:
        code = vc.get("code", "VERIFIER_RECOMPUTE_DEFECT")
        subtype = vc.get("subtype", "recompute_defect")
        summary = vc["summary"]
    else:
        is_schema_mismatch = bool(vd and vd.get("alignment") == "verifier_schema_mismatch")
        is_regex_defect = bool(
            (th and th.get("type") == "parser_hazard")
            or (vd and "namelist" in vd.get("item", ""))
        )
        if is_schema_mismatch:
            code = "VERIFIER_SCHEMA_MISMATCH"
            subtype = "schema_mismatch"
        elif is_regex_defect:
            code = "VERIFIER_REGEX_OR_PARSER_DEFECT"
            subtype = "regex_or_parser_defect"
        else:
            code = "VERIFIER_HIDDEN_CONTRACT"
            subtype = "hidden_contract"
        summary = (
            vd["details"]
            if vd
            else (th["summary"] if th else "Verifier parser/contract defect rejected valid agent output.")
        )

    ev_refs = []
    if vc:
        ev_refs.append(vc["obs_id"])
    if vd:
        ev_refs.append(vd["contract_id"])
    if th:
        ev_refs.append(th["obs_id"])
    if any(v["obs_id"] == "ver:fail_log" for v in verifier_obs):
        ev_refs.append("ver:fail_log")

    fail_summary = next(
        (v["summary"] for v in verifier_obs if v["obs_id"] == "ver:fail_log"),
        summary,
    )

    contributing = []
    if not vc:
        contributing.append(
            attach_confidence_metadata(
                {
                    "category": "case",
                    "subtype": "ambiguous_contract",
                    "code": "CASE_AMBIGUOUS_CONTRACT",
                    "summary": "Prompt did not explicitly constrain input/log syntax formatting assumed by `verify.py`.",
                },
                direct_causal_evidence=1,
            )
        )

    prc = attach_confidence_metadata(
        {
            "category": "verifier",
            "subtype": subtype,
            "code": code,
            "summary": summary,
        },
        direct_causal_evidence=len(ev_refs),
        cross_source_corroboration=1,
    )
    h1 = attach_confidence_metadata(
        {
            "hypothesis_id": "H1",
            "category": "verifier",
            "subtype": subtype,
            "claim": summary,
            "evidence_for": ev_refs,
            "evidence_against": [],
            "missing_evidence": [],
            "counterfactual_test": "Fix `tests/verify.py` internal file/parser logic and re-verify existing trial artifacts.",
        },
        direct_causal_evidence=len(ev_refs),
        cross_source_corroboration=1,
    )
    h2 = attach_confidence_metadata(
        {
            "hypothesis_id": "H2",
            "category": "agent",
            "subtype": "result_validation",
            "claim": "Agent produced invalid or missing simulation results.",
            "evidence_for": [],
            "evidence_against": ev_refs,
            "missing_evidence": [],
            "counterfactual_test": "Inspect agent's workspace outputs against `instruction.md` requirements.",
        },
        direct_causal_evidence=0,
        contradicting_evidence=1,
    )

    return {
        "schema_version": SCHEMA_VERSION,
        "case_id": case_id,
        "trial_name": trial_name,
        "verdict": "failed",
        "failure_stage": "verifier_execution",
        "detection_stage": "verifier_execution",
        "first_unrecovered_deviation": {
            "status": "identified",
            "event_ref": ev_refs[0] if ev_refs else "ver:fail_log",
            "timestamp": (runtime.get("stages", {}).get("verifier") or {}).get("started_at"),
            "summary": summary,
        },
        "failure_manifestation": {
            "type": "verifier_internal_crash" if vc else "verifier_false_rejection",
            "summary": fail_summary,
        },
        "primary_root_cause": prc,
        "contributing_factors": contributing,
        "competing_hypotheses": [h1, h2],
        "evidence_refs": ev_refs,
        "excluded_hypotheses": [
            {
                "hypothesis_id": "H2",
                "category": "agent",
                "reason": (
                    "Verifier crashed internally on its own reference/temp file before validating agent output."
                    if vc
                    else "Agent's simulation outputs satisfied the prompt contract before hitting the causally bound verifier parser/header defect."
                ),
            }
        ],
        "recommended_actions": [
            {
                "owner": "Verifier",
                "action": (
                    f"Fix `tests/verify.py` ({code}): ensure internal reference paths exist and use robust namelist/float/header parsing."
                ),
            }
        ],
        "skill_prescription": None,
    }
