#!/usr/bin/env python3
"""
Gate 0 - the trial passed verification; there is no failure to attribute.

Generated by extracting the corresponding region of the former
`analyze_case._build_raw_causal_attribution` verbatim; the gate bodies below are
byte-identical to the original logic, with `ctx.trace.record(...)` calls injected
at the abstain and match points.
"""
from __future__ import annotations

from confidence import attach_confidence_metadata

from typing import Any, Dict, Optional

from ..context import AttributionContext



def gate0_passed(ctx: AttributionContext) -> Optional[Dict[str, Any]]:
    case_id = ctx.case_id
    reward = ctx.reward
    trial_name = ctx.trial_name
    verification_status = ctx.verification_status

    if not ((verification_status == "passed") or (reward is not None and reward >= 1.0)):
        ctx.trace.record(
            gate_id="gate0_passed",
            matched=False,
            reason="trial did not pass verification",
            checks={"verification_status": verification_status, "reward": reward},
        )
        return None

    prc = attach_confidence_metadata(
        {
            "category": "none",
            "subtype": "none",
            "code": "NONE",
            "summary": "No failure occurred; trial completed and passed verification (reward >= 1.0).",
        },
        verdict_passed=True,
    )
    ctx.trace.record(
        gate_id="gate0_passed",
        matched=True,
        reason="trial passed verification (reward >= 1.0)",
        checks={"verification_status": verification_status, "reward": reward},
    )

    return {
        "schema_version": "failure-analysis-v1",
        "case_id": case_id,
        "trial_name": trial_name,
        "verdict": "passed",
        "failure_stage": "none",
        "detection_stage": "verifier_execution",
        "first_unrecovered_deviation": None,
        "failure_manifestation": {
            "type": "none",
            "summary": "Trial completed and passed all verifier checks (reward=1.0).",
        },
        "primary_root_cause": prc,
        "contributing_factors": [],
        "competing_hypotheses": [],
        "evidence_refs": ["art:trial_result"],
        "excluded_hypotheses": [],
        "recommended_actions": [],
        "skill_prescription": None,
    }
